---
jobs:
- name: test-pr
  build_logs_to_retain: 30
  serial: true
  plan:
  - get: test-pull-request
    trigger: true
  - get: golang
  - task: test-pr
    image:
      name: golang
      tag: 1.11-alpine3.8
    file: test-pull-request/ci/tasks/test-pull-request.yml

- name: test-pull-request
  type: pull-request
  source:
    private_key: ((github-private-key))
    access_token: ((github-access-token))
    repo: morningconsult/docker-credential-vault-login
    uri: ((github-repo))
    base: master

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr