---
# ====================================
#
#            RESOURCE TYPES
#
# ====================================
resource_types:
- name: slack-alert
  type: registry-image
  source:
    repository: arbourd/concourse-slack-alert-resource

- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource


# ====================================
#
#            RESOURCES
#
# ====================================
resources:
- name: test-pull-request
  type: pull-request
  icon: github-circle
  source:
    repository: morningconsult/docker-credential-vault-login
    access_token: ((github-token))

- name: docker-credential-vault-login
  type: git
  icon: github-circle
  source:
    uri: ((github-repo))
    private_key: ((github-private-key))
    branch: master
    clean_tags: true

- name: docker-credential-vault-login-bumped
  type: git
  icon: github-circle
  source:
    uri: ((github-repo))
    private_key: ((github-private-key))
    branch: master

- name: golang
  type: registry-image
  icon: golf
  source:
    repository: golang
    tag: 1.12.9-alpine3.10

- name: python
  type: registry-image
  icon: language-python
  source:
    repository: python
    tag: 3.7.3-alpine3.9

- name: slack
  type: slack-alert
  icon: slack
  source:
    url: ((slack-webhook))
    channel: '#build'

# ====================================
#
#            JOBS
#
# ====================================
jobs:
- name: validate-pull-request
  build_logs_to_retain: 30
  serial: true
  plan:
  - in_parallel:
    - get: test-pull-request
      trigger: true
    - get: golang
  - put: test-pull-request
    params:
      path: test-pull-request
      status: pending
      context: test-pr
  - task: validate-pull-request
    image: golang
    file: test-pull-request/ci/tasks/validate.yml
    input_mapping: {repo: test-pull-request}
    on_failure:
      put: test-pull-request
      params:
        path: test-pull-request
        status: failure
        context: test-pr
    on_abort:
      put: test-pull-request
      params:
        path: test-pull-request
        status: error
        context: test-pr
  - put: test-pull-request
    params:
      path: test-pull-request
      status: success
      context: test-pr

- name: validate-master
  build_logs_to_retain: 30
  serial: true
  plan:
  - in_parallel:
    - get: docker-credential-vault-login
      trigger: true
    - get: golang
  - task: validate-master
    image: golang
    file: docker-credential-vault-login/ci/tasks/validate.yml
    input_mapping: {repo: docker-credential-vault-login}
    on_failure:
      put: slack
      params: {alert_type: failed}
    on_abort:
      put: slack
      params: {alert_type: aborted}

- name: build-new-release
  build_logs_to_retain: 30
  serial: true
  plan:
  - in_parallel:
    - get: docker-credential-vault-login
      trigger: true
      passed: [validate-master]
    - get: python
  - task: build-release
    image: python
    file: docker-credential-vault-login/ci/tasks/build-release.yml
    input_mapping: {repo: docker-credential-vault-login}
    output_mapping: {repo-dirty: docker-credential-vault-login-dirty}
    params:
      GITHUB_ACTOR: ((github-actor))
      GITHUB_EMAIL: ((github-email))
    on_success:
      put: docker-credential-vault-login-bumped
      params:
        repository: docker-credential-vault-login-dirty
        merge: true
    on_failure:
      put: slack
      params: {alert_type: failed}
    on_abort:
      put: slack
      params: {alert_type: aborted}

- name: publish-release
  build_logs_to_retain: 30
  serial: true
  plan:
  - in_parallel:
    - get: docker-credential-vault-login-bumped
      trigger: true
      passed: [build-new-release]
    - get: golang
  - task: test-and-build
    image: golang
    file: docker-credential-vault-login-bumped/ci/tasks/publish-release.yml
    input_mapping: {repo: docker-credential-vault-login-bumped}
    params:
      GITHUB_TOKEN: ((github-token))
    on_failure:
      put: slack
      params: {alert_type: failed}
    on_abort:
      put: slack
      params: {alert_type: aborted}
